name: Update

on:
  schedule:
    - cron:  '08 8 * * 3'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/modm-ext/modm-build-cortex-m:latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Configure Git
        run: |
          git config --global user.email "bot@modm.io"
          git config --global user.name "modm update bot"
          git config --global --add safe.directory /__w/pico-sdk-partial/pico-sdk-partial
      - name: Run update.py script
        run: |
          python3 update.py
      - name: Git push
        run: |
          git push origin main
      - name: Keep Alive
        if: always()
        uses: gautamkrishnar/keepalive-workflow@v1
        with:
          committer_username: modm update bot
          committer_email: bot@modm.io
